### ISSUE TITLE
`npm run build` not compiling ES6

### ISSUE THREAD

**Issue by juanbrujo** [KingPixil/moon-cli#12]
this error `SyntaxError: Unexpected token: operator (>) while parsing file` due I was using fat arrows:

```
axios.get(api)
        .then(response => {
        ...
```

**Comment by kbrsh** [comment]
Is this error coming from Uglify? If so, it is because Uglify doesn't support ES6 by default. Add `babelify` as a browserify transform (after `moonify`).

**Comment by juanbrujo** [comment]
yep, from Uglifyfy

**Comment by kbrsh** [comment]
Alright, to fix it, add the `babelify` transform **before** the `uglifyify` transform in `build/build.js`. Something like:

```js
bundler.transform('babelify')
  .transform({
    global: true,
    ignore: [
      '*.moon',
      '*.css'
    ]
  }, 'uglifyify')
  .plugin('moonify/plugins/extract-css.js')
  .bundle()
  .pipe(fs.createWriteStream(tmpJSPath));
```
