### ISSUE TITLE
First run does not load JS

### ISSUE THREAD

**Issue by christopherwk210** [KingPixil/moon-cli#13]
When the first `npm run dev` is run and the page is opened in the browser, the JavaScript appears to not be loading... Inspecting the contents of the page shows all of the correct HTML, but the page itself is blank, apparently indicating that Moon has not loaded. As soon as the page is refreshed it works properly, and continues to work properly from then on.

Testing on macOS Sierra 10.12.5 with Chrome 59.

**Comment by kbrsh** [comment]
I'm not sure if this can be classified as an issue, but more of an inconvenience. This happens because `watchify` takes longer to start up than `http-server`, and it builds the files after the server is loaded.

**Comment by christopherwk210** [comment]
Ah, I see. Could probably be fixed by switching to gulp or webpack in the future, but either way it's not really an issue. Thanks!

**Comment by kbrsh** [comment]
Yeah, I'm currently working on the template to use Webpack.
