### ISSUE TITLE
How can I use ES6 Import in MoonJS instead of ES5 require()?

### ISSUE THREAD

**Issue by ghost** [KingPixil/moon-cli#16]
Hello.
What's the best way to use ES6 Import syntax in MoonJS (instead of require())?

Like this:
```javascript
//const Moon = require("moonjs");
//require("./components/header.moon")(Moon);

import Moon from "moonjs"
import Header from "./components/header.moon"

new Moon({
  el: "#app"
});
```

Thank you in advance!

**Comment by kbrsh** [comment]
You can definitely use `import`. A `.moon` file will export a function that must be called with `Moon` as the parameter to install a component.

```js
import Moon from "moonjs"
import Header from "./components/header.moon"

Header(Moon);

new Moon({
  el: "#app"
});
```

**Comment by zakharkang** [comment]
Thanks for the answer!
And I have another question. Does the Brunch support other build tools besides _Browserify_?

**Comment by ghost** [comment]
Thanks for the answer!
And I have another question. Does the MoonJS support (or will) other build tools besides _Browserify_?

**Comment by kbrsh** [comment]
Yup! Moon will definitely start moving to Webpack.

**Comment by sadeghbarati** [comment]
@kbrsh 
Please include Template for **`moon-simple-webpack`** and **`advanced-webpack`** like `vue.js templates`

 remove **`build`** folder and add **`webpack.config`** for handle all things done with build folder

and pls include **`moon-loader`** for webpack like most javascript library :)

in `version1`  **[`moon-cli`]**  moving to webpack ? and we can use JUST import for components and don't need to add `(Moon)`parameter to install component like 

`Header(Moon);`

 after `import` ?

and we have to import all component in scripts.js ? cuz moon create component globaly ?
