### ISSUE TITLE
[Windows] error with NODE_ENV assignments in package.json

### ISSUE THREAD

**Issue by bmcminn** [KingPixil/moon-cli#4]
OS: Win 7 Professional 64bit
Node: 7.2.0
NPM: 3.10.9

-----

Windows can't handle implicitly assigning environment values and requires the `set` command. Secondary issue is that Windows also doesn't handle multiple inline program calls nicely, which requires a `&&` between chained program calls.

    Q:\github\blargh  (blargh@0.0.0)
    λ npm run dev

    > blargh@0.0.0 dev Q:\github\blargh
    > npm-run-all --parallel watch serve watch-css bundle-css

    > blargh@0.0.0 watch Q:\github\blargh
    > NODE_ENV='development' ./node_modules/.bin/watchify -vd -e js/scripts.js -o dist/js/build.min.js

    'NODE_ENV' is not recognized as an internal or external command,
    operable program or batch file.

I can't test this to see if it works in Unix environments, but it should work just fine, though a bit more robust.

    "scripts": {
        "watch": "set NODE_ENV=development && ./node_modules/.bin/watchify -vd -e js/scripts.js -o dist/js/build.min.js",
        "serve": "./node_modules/.bin/http-server -o -c 1 -a localhost",
        "bundle-css": "node ./build/bundle-css.js",
        "watch-css": "node ./build/watch.js",
        "dev": "./node_modules/.bin/npm-run-all --parallel watch serve watch-css bundle-css",
        "build": "set NODE_ENV=production && node build/build.js"
    },

**Comment by kbrsh** [comment]
Should be fixed
