### ISSUE TITLE
[Windows] NPM scripts do not need to reference ./node_modules/.bin binaries

### ISSUE THREAD

**Issue by bmcminn** [KingPixil/moon-cli#5]
OS: Win 7 Professional 64bit
Node: 7.2.0
NPM: 3.10.9

-----

This works fine in Unix, but in Windows, Node has a really hard time deciding between the `bash` and `.cmd` utitlies in `node_modules/.bin`.

    Q:\github\blargh  (blargh@0.0.0)
    λ npm run dev

    > blargh@0.0.0 dev Q:\github\blargh
    > npm-run-all --parallel watch serve watch-css bundle-css

    > blargh@0.0.0 watch Q:\github\blargh
    > set NODE_ENV=development && ./node_modules/.bin/watchify -vd -e js/scripts.js -o dist/js/build.min.js

    > blargh@0.0.0 serve Q:\github\blargh
    > http-server -o -c 1 -a localhost

    '.' is not recognized as an internal or external command,
    operable program or batch file.

    <<...truncated for brevity...>>

Since you're already running these commands with `npm run`, Node already has the `node_modules/.bin` folder loaded into it's environment, so you can simply call the utility directly and Windows will automatically infer which utility file to call:

    "scripts": {
        "watch": "set NODE_ENV=development && watchify -vd -e js/scripts.js -o dist/js/build.min.js",
        "serve": "http-server -o -c 1 -a localhost",
        "bundle-css": "node ./build/bundle-css.js",
        "watch-css": "node ./build/watch.js",
        "dev": "npm-run-all --parallel watch serve watch-css bundle-css",
        "build": "set NODE_ENV=production && node build/build.js"
    },

**Comment by kbrsh** [comment]
Try regenerating the project (I updated the template) and running it again.

**Comment by kbrsh** [comment]
Fixed
