### ISSUE TITLE
[Build] stylesheet hash echoed to index.html as build.[object Object].css

### ISSUE THREAD

**Issue by bmcminn** [KingPixil/moon-cli#6]
Running the npm `build` script causes a strange error where the `dist/index.html` file references a `build.[object Object].css` file.

```html
<link rel="stylesheet" type="text/css" href="./css/build.[object Object].css"/>
```

Determined this is due to `bundle-css` compiling a `hash` value as part of the string name for specific builds, however the `dist/css` folder only contains `build.min.css` which wouldn't be loaded anyway.

**Comment by kbrsh** [comment]
This is odd. In the `build/build.js` file can you add:

```js
// ~line 39
cssHash = require("./bundle-css.js");
console.log(JSON.stringify(cssHash));
```

Run it again and let me know of the output.

**Comment by kbrsh** [comment]
Should be fixed
